// <auto-generated />
using System;
using BusTracking.Infrastructure.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusTracking.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240730111931_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.Employees", b =>
                {
                    b.Property<int>("Rfid")
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gouvernement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PointedBus")
                        .HasColumnType("bit");

                    b.Property<bool?>("PointedIn")
                        .HasColumnType("bit");

                    b.Property<bool?>("PointedOut")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rfid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.Societe", b =>
                {
                    b.Property<int>("SocieteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocieteId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocieteId");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.TrackingEvent", b =>
                {
                    b.Property<int>("TrackingEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingEventID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Rfid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackingEventID");

                    b.HasIndex("Rfid");

                    b.ToTable("TrackingEvent");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocieteId")
                        .HasColumnType("int");

                    b.HasKey("Login");

                    b.HasIndex("SocieteId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.TrackingEvent", b =>
                {
                    b.HasOne("BusTracking.Domain.ENTITIES.Employees", "Employees")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("Rfid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.User", b =>
                {
                    b.HasOne("BusTracking.Domain.ENTITIES.Societe", "Societe")
                        .WithMany("Users")
                        .HasForeignKey("SocieteId");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.Employees", b =>
                {
                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("BusTracking.Domain.ENTITIES.Societe", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
